name: Build APK

on:
  push:
    branches:
      - main  # Altere para o nome da branch principal do seu projeto
  workflow_dispatch:  # Permite acionar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Ou a versão do Java que seu projeto usa
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build APK
        run: ./gradlew assembleDebug  # Ou assembleRelease, dependendo do que você quer

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk  # Caminho padrão para o APK gerado
